### ISSUE TITLE
Automatically upload artifacts

### ISSUE THREAD

**Issue by sagikazarmark** [sagikazarmark/setup-please-action#13]
Automatically upload artifacts for a given target.

Say you have an `:artifacts` rule in the repo root:

```
❯ plz query output :artifacts
plz-out/gen/checksums.txt
plz-out/gen/gogetgen_darwin_amd64.tar.gz
plz-out/gen/gogetgen_linux_amd64.tar.gz
```

Upload the output of that rule as separate artifacts, using the file name as the artifact name.

Currently you need to do something like this:

```yaml
      - name: Upload linux artifact
        uses: actions/upload-artifact@v1
        with:
          name: gogetgen_linux_amd64.tar.gz
          path: plz-out/gen/gogetgen_linux_amd64.tar.gz

      - name: Upload darwin artifact
        uses: actions/upload-artifact@v1
        with:
          name: gogetgen_darwin_amd64.tar.gz
          path: plz-out/gen/gogetgen_darwin_amd64.tar.gz

      - name: Upload checksums
        uses: actions/upload-artifact@v1
        with:
          name: checksums.txt
          path: plz-out/gen/checksums.txt
```

Some other ideas:

- Support multiple artifact rules
- Support artifact names (eg. generate a file with artifact names and match those with the files of the artifact rule)
