### ISSUE TITLE
Automatically add/fetch matrix

### ISSUE THREAD

**Issue by sagikazarmark** [sagikazarmark/setup-please-action#6]
In order to generate a unique name for logs, we need to fetch the matrix somehow.

Currently, user will have to add the following to their workflows when saving logs:

```yaml
      - name: Set up Please
        uses: sagikazarmark/setup-please-action@master
        with:
          save-logs: 'true'
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
```

See:
- https://github.com/8398a7/action-slack/issues/108#issuecomment-690093896
- https://github.com/actions/toolkit/issues/586
- https://github.com/actions/runner/issues/324
